kind: Deployment
apiVersion: apps/v1
metadata:
  name: passwordvault-api
  labels:
    app: passwordvault-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passwordvault-api
  template:
    metadata:
      labels:
        app: passwordvault-api
    spec:
      containers:
      - name: passwordvaultapi
        image: bjd145.azurecr.io/passwordvault/api:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets
          mountPath: "/azure-functions-host/Secrets"
        env:     
        - name: AzureWebJobsSecretStorageType
          value: files
        - name: cosmosdb
          valueFrom:
           secretKeyRef:
             name: secrets-passwordvault
             key: COSMOSDB_CONSTR
        - name: AesKey
          valueFrom:
           secretKeyRef:
             name: secrets-passwordvault
             key: AesKey
        - name: AesIV
          valueFrom:
           secretKeyRef:
             name: secrets-passwordvault
             key: AesIV
        - name: AzureWebJobsStorage
          valueFrom:
           secretKeyRef:
             name: secrets-passwordvault
             key: AzureWebJobsStorage
        resources:
          limits:
            memory: "256M"
            cpu: "0.1"         
      volumes:
       - name: secrets
         secret:
           secretName: azure-functions-secrets 
      imagePullSecrets:
        - name: registrykey

---

kind: Service
apiVersion: v1
metadata:
  name: passwordvault-api-svc
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 80
  selector:
    app: passwordvault-api
