apiVersion: v1
kind: Secret
metadata:
  name: azure-functions-secrets
type: Opaque
stringData:
  host.json: |-
    {
      "masterKey": {
        "name": "master",
        "value": "[MASTER_KEY]",
        "encrypted": false
      },
      "functionKeys": [ ]
    }
  httpTrigger.json: |-
    {
      "keys": [
        {
          "name": "default",
          "value": "[HOST_KEY]",
          "encrypted": false
        }
      ]
    }
---
apiVersion: v1
kind: Secret
metadata:
  name:  secrets-passwordvault
type: Opaque
data:
  AzureWebJobsStorage: 
  COSMOSDB_CONSTR: 
  AesKey: 
  AesIV: 
