kind: Deployment
apiVersion: apps/v1
metadata:
  name: cosmosdb
  labels:
    app: cosmosdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosmosdb
  template:
    metadata:
      labels:
        app: cosmosdb
    spec:
      containers:
      - name: cosmosdb
        image: microsoft/azure-cosmosdb-emulator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        volumeMounts:
          - mountPath: C:\CosmosDB.Emulator\CosmosDBEmulatorCert
            name: cosmosdbemulatorcert
      nodeSelector:
        beta.kubernetes.io/os: windows
      volumes:
      - name: cosmosdbemulatorcert
        emptyDir: {}

---

kind: Service
apiVersion: v1
metadata:
  name: cosmosdb-svc
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  selector:
    app: cosmosdb

