appgw:
    subscriptionId: [SUSBSCRIPTION.ID]
    resourceGroup: [APP_GATEWAY_RG]
    name: [APP_GATEWAY_NAME]

armAuth:
    type: aadPodIdentity
    identityResourceID: /subscriptions/[SUSBSCRIPTION.ID]/resourceGroups/MC_[K8S_MANAGED_RESOURCE_GROUP]/providers/Microsoft.ManagedIdentity/userAssignedIdentities/appgw-westus2
    identityClientID: [CLIENT_ID_OF_MSI]

rbac:
    enabled: true

aksClusterConfiguration:
    apiServerAddress: [K8S_API_SERVER].hcp.westus2.azmk8s.io 
