appgw:
    subscriptionId: [SUSBSCRIPTION.ID]
    resourceGroup: [APP_GATEWAY_RG]
    name: [APP_GATEWAY_NAME]

armAuth:
    type: aadPodIdentity
    identityResourceID: /subscriptions/bfafbd89-a2a3-43a5-af72-fb4ef0c514c1/resourceGroups/MC_[K8S_MANAGED_RESOURCE_GROUP]/providers/Microsoft.ManagedIdentity/userAssignedIdentities/appgw-central
    identityClientID:  [CLIENT_ID_OF_MSI]

rbac:
    enabled: true

aksClusterConfiguration:
    apiServerAddress: [K8S_API_SERVER].hcp.centralus.azmk8s.io
