trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  AAD_TENANT_ID:
  AAD_CLIENT_ID:
  AAD_REDIRECT_URL:
  functionUrl:
  environment:

steps:
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in **/*.env.$(environment)'
  inputs:
    rootDirectory: Source/passwordapp.ui
    targetFiles: '**/*.env.$(environment)'
    encoding: ascii
    escapeType: none

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in **/*.env'
  inputs:
    rootDirectory: Source/passwordapp.ui
    targetFiles: '**/*.env'
    encoding: ascii
    escapeType: none

- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: Source/passwordapp.ui
    verbose: false

- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: custom
    workingDir: Source/passwordapp.ui
    verbose: false
    customCommand: 'run build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop-production'
  inputs:
    PathtoPublish: Source/passwordapp.ui/dist
    ArtifactName: 'drop-production'
